### ISSUE TITLE
IPv4 data is not decoded

### ISSUE THREAD

**Issue by jannooo** [fooelisa/perl-net-sflow#2]
Hi,

I think I found a bug in Net::sFlow. I am receiving samples which include IPv4 data (verified with sflowtool), but it does not get decoded by Net::sFlow. 

After some debugging I found out that `_decodeFlowRecord()` is never run for `IPv4DATA_SFLOWv5` on the samples.

But if I add the line:

```
&_decodeIPv4Data(\$offset, $sFlowDatagramPackedRef, $sFlowSample);
```

within 

```
if ($flowTypeFormat == HEADERDATA_SFLOWv5) { 
...
} 
```

the IPv4 data gets decoded. 

Please let me know if you need any further informations.

**Comment by fooelisa** [comment]
Hi, would you happen to have a pcap of your sample data to check this out?

**Comment by ipcjk** [comment]
Just hacked some demo code  and found the same issue.

The perl module is looking for an 
enterprise = 0, format = 3,  IPv4-Header.

sflowtool indeed also supports decoding in 
enterprise = 0, format = 1, Raw Packet Header

My router does not emit an IPv4-header, but includes all necessary data inside the raw packet header. 

Basically we  need to code some way to call  _decodeIPv4Data and others from inside _decodeHeaderData.

**Comment by fooelisa** [comment]
The data decoded in _decodeIPv4Data is in an sFlow specific format. If your device exports the Raw Packet Header format, it will just contain a typical Eth/IP/etc structure, which can be decoded with any IP packet parser eg. NetPacket by passing HeaderBin to it. Hope this helps!

**Comment by ipcjk** [comment]
Yes, this will work.  Maybe we can add a hint like this one to the documentation?
